import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';

import '../globals.css';

import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import ResponsiveLayout from '@/components/layout/ResponsiveLayout';

const suit = localFont({
  src: '../../../public/assets/fonts/SUIT-Variable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-suit-variable',
});

export const metadata: Metadata = {
  title: 'FANMIX',
  description: 'Generated by create next app for FANMIX',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/assets/images/favicons/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/assets/images/favicons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/assets/images/favicons/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
      { url: '/assets/images/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
    ],
    apple: [
      { url: '/assets/images/icons/icon-180x180.png', sizes: '180x180', type: 'image/png' },
      { url: '/assets/images/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  themeColor: '#000000',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale} className={suit.variable}>
      <body className={suit.className}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ResponsiveLayout>{children}</ResponsiveLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
